/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AreaRule model module.
 * @module model/AreaRule
 * @version 1.0
 */
class AreaRule {
    /**
     * Constructs a new <code>AreaRule</code>.
     * @alias module:model/AreaRule
     */
    constructor() {

        AreaRule.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {}

    /**
     * Constructs a <code>AreaRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AreaRule} obj Optional instance to populate.
     * @return {module:model/AreaRule} The populated <code>AreaRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AreaRule();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('campaign_id')) {
                obj['campaign_id'] = ApiClient.convertToType(data['campaign_id'], 'Number');
            }
            if (data.hasOwnProperty('area_id')) {
                obj['area_id'] = ApiClient.convertToType(data['area_id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AreaRule.TypeEnum} type
 */
AreaRule.prototype['type'] = undefined;

/**
 * @member {Number} id
 */
AreaRule.prototype['id'] = undefined;

/**
 * @member {Number} campaign_id
 */
AreaRule.prototype['campaign_id'] = undefined;

/**
 * @member {Number} area_id
 */
AreaRule.prototype['area_id'] = undefined;

/**
 * @member {Date} created_at
 */
AreaRule.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
AreaRule.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
AreaRule['TypeEnum'] = {

    /**
     * value: "AreaRule"
     * @const
     */
    "AreaRule": "AreaRule"
};



export default AreaRule;