/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BudgetRule model module.
 * @module model/BudgetRule
 * @version 1.0
 */
class BudgetRule {
    /**
     * Constructs a new <code>BudgetRule</code>.
     * @alias module:model/BudgetRule
     * @param timeframe {module:model/BudgetRule.TimeframeEnum} Timeframe within which the budget will be checked
     * @param budget {Number} 
     */
    constructor(timeframe, budget) {

        BudgetRule.initialize(this, timeframe, budget);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, timeframe, budget) {
        obj['timeframe'] = timeframe;
        obj['budget'] = budget;
    }

    /**
     * Constructs a <code>BudgetRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BudgetRule} obj Optional instance to populate.
     * @return {module:model/BudgetRule} The populated <code>BudgetRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BudgetRule();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('campaign_id')) {
                obj['campaign_id'] = ApiClient.convertToType(data['campaign_id'], 'Number');
            }
            if (data.hasOwnProperty('timeframe')) {
                obj['timeframe'] = ApiClient.convertToType(data['timeframe'], 'String');
            }
            if (data.hasOwnProperty('budget')) {
                obj['budget'] = ApiClient.convertToType(data['budget'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BudgetRule.TypeEnum} type
 */
BudgetRule.prototype['type'] = undefined;

/**
 * @member {Number} id
 */
BudgetRule.prototype['id'] = undefined;

/**
 * @member {Number} campaign_id
 */
BudgetRule.prototype['campaign_id'] = undefined;

/**
 * Timeframe within which the budget will be checked
 * @member {module:model/BudgetRule.TimeframeEnum} timeframe
 */
BudgetRule.prototype['timeframe'] = undefined;

/**
 * @member {Number} budget
 */
BudgetRule.prototype['budget'] = undefined;

/**
 * @member {Date} created_at
 */
BudgetRule.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
BudgetRule.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
BudgetRule['TypeEnum'] = {

    /**
     * value: "BudgetRule"
     * @const
     */
    "BudgetRule": "BudgetRule"
};


/**
 * Allowed values for the <code>timeframe</code> property.
 * @enum {String}
 * @readonly
 */
BudgetRule['TimeframeEnum'] = {

    /**
     * value: "year"
     * @const
     */
    "year": "year",

    /**
     * value: "quarter"
     * @const
     */
    "quarter": "quarter",

    /**
     * value: "month"
     * @const
     */
    "month": "month",

    /**
     * value: "week"
     * @const
     */
    "week": "week",

    /**
     * value: "sunday_week"
     * @const
     */
    "sunday_week": "sunday_week",

    /**
     * value: "day"
     * @const
     */
    "day": "day",

    /**
     * value: "hour"
     * @const
     */
    "hour": "hour"
};



export default BudgetRule;