/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CategoryRule model module.
 * @module model/CategoryRule
 * @version 1.0
 */
class CategoryRule {
    /**
     * Constructs a new <code>CategoryRule</code>.
     * @alias module:model/CategoryRule
     * @param ruleType {module:model/CategoryRule.RuleTypeEnum} 
     * @param tags {Array.<String>} 
     */
    constructor(ruleType, tags) {

        CategoryRule.initialize(this, ruleType, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ruleType, tags) {
        obj['rule_type'] = ruleType;
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>CategoryRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategoryRule} obj Optional instance to populate.
     * @return {module:model/CategoryRule} The populated <code>CategoryRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryRule();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('campaign_id')) {
                obj['campaign_id'] = ApiClient.convertToType(data['campaign_id'], 'Number');
            }
            if (data.hasOwnProperty('category_id')) {
                obj['category_id'] = ApiClient.convertToType(data['category_id'], 'Number');
            }
            if (data.hasOwnProperty('rule_type')) {
                obj['rule_type'] = ApiClient.convertToType(data['rule_type'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CategoryRule.TypeEnum} type
 */
CategoryRule.prototype['type'] = undefined;

/**
 * @member {Number} id
 */
CategoryRule.prototype['id'] = undefined;

/**
 * @member {Number} campaign_id
 */
CategoryRule.prototype['campaign_id'] = undefined;

/**
 * @member {Number} category_id
 */
CategoryRule.prototype['category_id'] = undefined;

/**
 * @member {module:model/CategoryRule.RuleTypeEnum} rule_type
 */
CategoryRule.prototype['rule_type'] = undefined;

/**
 * @member {Array.<String>} tags
 */
CategoryRule.prototype['tags'] = undefined;

/**
 * @member {Date} created_at
 */
CategoryRule.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
CategoryRule.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CategoryRule['TypeEnum'] = {

    /**
     * value: "CategoryRule"
     * @const
     */
    "CategoryRule": "CategoryRule"
};


/**
 * Allowed values for the <code>rule_type</code> property.
 * @enum {String}
 * @readonly
 */
CategoryRule['RuleTypeEnum'] = {

    /**
     * value: "any_of"
     * @const
     */
    "any_of": "any_of",

    /**
     * value: "none_of"
     * @const
     */
    "none_of": "none_of"
};



export default CategoryRule;