/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PerCustomerRule model module.
 * @module model/PerCustomerRule
 * @version 1.0
 */
class PerCustomerRule {
    /**
     * Constructs a new <code>PerCustomerRule</code>.
     * @alias module:model/PerCustomerRule
     * @param maxRedemptions {Number} Number of times a single customer can redeem in given campaign.
     */
    constructor(maxRedemptions) {

        PerCustomerRule.initialize(this, maxRedemptions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, maxRedemptions) {
        obj['max_redemptions'] = maxRedemptions;
    }

    /**
     * Constructs a <code>PerCustomerRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PerCustomerRule} obj Optional instance to populate.
     * @return {module:model/PerCustomerRule} The populated <code>PerCustomerRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PerCustomerRule();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('campaign_id')) {
                obj['campaign_id'] = ApiClient.convertToType(data['campaign_id'], 'Number');
            }
            if (data.hasOwnProperty('max_redemptions')) {
                obj['max_redemptions'] = ApiClient.convertToType(data['max_redemptions'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PerCustomerRule.TypeEnum} type
 */
PerCustomerRule.prototype['type'] = undefined;

/**
 * @member {Number} id
 */
PerCustomerRule.prototype['id'] = undefined;

/**
 * @member {Number} campaign_id
 */
PerCustomerRule.prototype['campaign_id'] = undefined;

/**
 * Number of times a single customer can redeem in given campaign.
 * @member {Number} max_redemptions
 */
PerCustomerRule.prototype['max_redemptions'] = undefined;

/**
 * @member {Date} created_at
 */
PerCustomerRule.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
PerCustomerRule.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PerCustomerRule['TypeEnum'] = {

    /**
     * value: "PerCustomerRule"
     * @const
     */
    "PerCustomerRule": "PerCustomerRule"
};



export default PerCustomerRule;