/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RedemptionCategories model module.
 * @module model/RedemptionCategories
 * @version 1.0
 */
class RedemptionCategories {
    /**
     * Constructs a new <code>RedemptionCategories</code>.
     * @alias module:model/RedemptionCategories
     */
    constructor() {

        RedemptionCategories.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {}

    /**
     * Constructs a <code>RedemptionCategories</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RedemptionCategories} obj Optional instance to populate.
     * @return {module:model/RedemptionCategories} The populated <code>RedemptionCategories</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RedemptionCategories();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
RedemptionCategories.prototype['name'] = undefined;

/**
 * @member {String} tag
 */
RedemptionCategories.prototype['tag'] = undefined;






export default RedemptionCategories;