/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TimeOfOrderRule model module.
 * @module model/TimeOfOrderRule
 * @version 1.0
 */
class TimeOfOrderRule {
    /**
     * Constructs a new <code>TimeOfOrderRule</code>.
     * @alias module:model/TimeOfOrderRule
     */
    constructor() {

        TimeOfOrderRule.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {}

    /**
     * Constructs a <code>TimeOfOrderRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimeOfOrderRule} obj Optional instance to populate.
     * @return {module:model/TimeOfOrderRule} The populated <code>TimeOfOrderRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeOfOrderRule();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('campaign_id')) {
                obj['campaign_id'] = ApiClient.convertToType(data['campaign_id'], 'Number');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Date');
            }
            if (data.hasOwnProperty('end_time')) {
                obj['end_time'] = ApiClient.convertToType(data['end_time'], 'Date');
            }
            if (data.hasOwnProperty('day_of_week')) {
                obj['day_of_week'] = ApiClient.convertToType(data['day_of_week'], 'Number');
            }
            if (data.hasOwnProperty('time_zone')) {
                obj['time_zone'] = ApiClient.convertToType(data['time_zone'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TimeOfOrderRule.TypeEnum} type
 */
TimeOfOrderRule.prototype['type'] = undefined;

/**
 * @member {Number} id
 */
TimeOfOrderRule.prototype['id'] = undefined;

/**
 * @member {Number} campaign_id
 */
TimeOfOrderRule.prototype['campaign_id'] = undefined;

/**
 * @member {Date} start_time
 */
TimeOfOrderRule.prototype['start_time'] = undefined;

/**
 * @member {Date} end_time
 */
TimeOfOrderRule.prototype['end_time'] = undefined;

/**
 * Sunday is zero.
 * @member {Number} day_of_week
 */
TimeOfOrderRule.prototype['day_of_week'] = undefined;

/**
 * Time zone name as defined in the [tz database](http://www.iana.org/time-zones) (e.g. Europe/London)
 * @member {String} time_zone
 */
TimeOfOrderRule.prototype['time_zone'] = undefined;

/**
 * @member {Date} created_at
 */
TimeOfOrderRule.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
TimeOfOrderRule.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
TimeOfOrderRule['TypeEnum'] = {

    /**
     * value: "TimeOfOrderRule"
     * @const
     */
    "TimeOfOrderRule": "TimeOfOrderRule"
};



export default TimeOfOrderRule;