/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Trigger model module.
 * @module model/Trigger
 * @version 2.0.0
 */
class Trigger {
    /**
     * Constructs a new <code>Trigger</code>.
     * @alias module:model/Trigger
     * @param type {module:model/Trigger.TypeEnum} 
     */
    constructor(type) {

        Trigger.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) {
        obj['type'] = type;
    }

    /**
     * Constructs a <code>Trigger</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Trigger} obj Optional instance to populate.
     * @return {module:model/Trigger} The populated <code>Trigger</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Trigger();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('customer_identifier')) {
                obj['customer_identifier'] = ApiClient.convertToType(data['customer_identifier'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Trigger.TypeEnum} type
 */
Trigger.prototype['type'] = undefined;

/**
 * Custom action name, your campaign is triggered on
 * @member {String} name
 */
Trigger.prototype['name'] = undefined;

/**
 * A string uniquely identifying customer in your system. Please check customers API.
 * @member {String} customer_identifier
 */
Trigger.prototype['customer_identifier'] = undefined;

/**
 * @member {Date} created_at
 */
Trigger.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Trigger.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Trigger['TypeEnum'] = {

    /**
     * value: "custom"
     * @const
     */
    "custom": "custom"
};



export default Trigger;