/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 2.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     * @param email {String} 
     * @param role {module:model/User.RoleEnum} 
     * @param accessScope {module:model/User.AccessScopeEnum} 
     */
    constructor(email, role, accessScope) {

        User.initialize(this, email, role, accessScope);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, role, accessScope) {
        obj['email'] = email;
        obj['role'] = role;
        obj['access_scope'] = accessScope;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('team')) {
                obj['team'] = ApiClient.convertToType(data['team'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('access_scope')) {
                obj['access_scope'] = ApiClient.convertToType(data['access_scope'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/User.TypeEnum} type
 */
User.prototype['type'] = undefined;

/**
 * @member {Number} id
 */
User.prototype['id'] = undefined;

/**
 * @member {String} name
 */
User.prototype['name'] = undefined;

/**
 * @member {String} email
 */
User.prototype['email'] = undefined;

/**
 * @member {String} team
 */
User.prototype['team'] = undefined;

/**
 * @member {module:model/User.RoleEnum} role
 */
User.prototype['role'] = undefined;

/**
 * @member {module:model/User.AccessScopeEnum} access_scope
 */
User.prototype['access_scope'] = undefined;

/**
 * @member {Boolean} active
 */
User.prototype['active'] = undefined;

/**
 * @member {Date} created_at
 */
User.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
User.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
User['TypeEnum'] = {

    /**
     * value: "User"
     * @const
     */
    "User": "User"
};


/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
User['RoleEnum'] = {

    /**
     * value: "admin"
     * @const
     */
    "admin": "admin",

    /**
     * value: "point_of_distribution"
     * @const
     */
    "point_of_distribution": "point_of_distribution",

    /**
     * value: "point_of_sale"
     * @const
     */
    "point_of_sale": "point_of_sale"
};


/**
 * Allowed values for the <code>access_scope</code> property.
 * @enum {String}
 * @readonly
 */
User['AccessScopeEnum'] = {

    /**
     * value: "project"
     * @const
     */
    "project": "project",

    /**
     * value: "campaign"
     * @const
     */
    "campaign": "campaign",

    /**
     * value: "team"
     * @const
     */
    "team": "team"
};



export default User;