/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CampaignCreatedBy model module.
 * @module Vouchery/CampaignCreatedBy
 * @version 2.0.0
 */
class CampaignCreatedBy {
    /**
     * Constructs a new <code>CampaignCreatedBy</code>.
     * @alias module:Vouchery/CampaignCreatedBy
     */
    constructor() {

        CampaignCreatedBy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {}

    /**
     * Constructs a <code>CampaignCreatedBy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Vouchery/CampaignCreatedBy} obj Optional instance to populate.
     * @return {module:Vouchery/CampaignCreatedBy} The populated <code>CampaignCreatedBy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CampaignCreatedBy();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CampaignCreatedBy.prototype['name'] = undefined;

/**
 * @member {String} email
 */
CampaignCreatedBy.prototype['email'] = undefined;






export default CampaignCreatedBy;