/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Category model module.
 * @module Vouchery/Category
 * @version 2.0.0
 */
class Category {
    /**
     * Constructs a new <code>Category</code>.
     * @alias module:Vouchery/Category
     * @param name {String} 
     * @param tags {Array.<String>} 
     */
    constructor(name, tags) {

        Category.initialize(this, name, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, tags) {
        obj['name'] = name;
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>Category</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Vouchery/Category} obj Optional instance to populate.
     * @return {module:Vouchery/Category} The populated <code>Category</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Category();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('category_type')) {
                obj['category_type'] = ApiClient.convertToType(data['category_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Category.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Category.prototype['name'] = undefined;

/**
 * @member {Array.<String>} tags
 */
Category.prototype['tags'] = undefined;

/**
 * @member {Date} created_at
 */
Category.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Category.prototype['updated_at'] = undefined;

/**
 * @member {module:Vouchery/Category.CategoryTypeEnum} category_type
 */
Category.prototype['category_type'] = undefined;





/**
 * Allowed values for the <code>category_type</code> property.
 * @enum {String}
 * @readonly
 */
Category['CategoryTypeEnum'] = {

    /**
     * value: "additional"
     * @const
     */
    "additional": "additional",

    /**
     * value: "customer"
     * @const
     */
    "customer": "customer",

    /**
     * value: "product"
     * @const
     */
    "product": "product"
};



export default Category;