/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RewardAddPoints model module.
 * @module Vouchery/RewardAddPoints
 * @version 2.0.0
 */
class RewardAddPoints {
    /**
     * Constructs a new <code>RewardAddPoints</code>.
     * @alias module:Vouchery/RewardAddPoints
     * @param type {module:Vouchery/RewardAddPoints.TypeEnum} 
     * @param value {Number} Number of loyalty points to add.
     */
    constructor(type, value) {

        RewardAddPoints.initialize(this, type, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, value) {
        obj['type'] = type;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>RewardAddPoints</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Vouchery/RewardAddPoints} obj Optional instance to populate.
     * @return {module:Vouchery/RewardAddPoints} The populated <code>RewardAddPoints</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RewardAddPoints();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:Vouchery/RewardAddPoints.TypeEnum} type
 */
RewardAddPoints.prototype['type'] = undefined;

/**
 * @member {String} title
 */
RewardAddPoints.prototype['title'] = undefined;

/**
 * @member {String} description
 */
RewardAddPoints.prototype['description'] = undefined;

/**
 * Number of loyalty points to add.
 * @member {Number} value
 */
RewardAddPoints.prototype['value'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
RewardAddPoints['TypeEnum'] = {

    /**
     * value: "AddPoints"
     * @const
     */
    "AddPoints": "AddPoints"
};



export default RewardAddPoints;