/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RuleAdditionalCategory model module.
 * @module Vouchery/RuleAdditionalCategory
 * @version 2.0.0
 */
class RuleAdditionalCategory {
    /**
     * Constructs a new <code>RuleAdditionalCategory</code>.
     * @alias module:Vouchery/RuleAdditionalCategory
     * @param type {module:Vouchery/RuleAdditionalCategory.TypeEnum} 
     * @param categoryType {module:Vouchery/RuleAdditionalCategory.CategoryTypeEnum} 
     * @param matchingType {module:Vouchery/RuleAdditionalCategory.MatchingTypeEnum} any_of means that all products should have tags in mentioned category. none_of - products shouldn't have tags.
     * @param tags {Array.<String>} 
     */
    constructor(type, categoryType, matchingType, tags) {

        RuleAdditionalCategory.initialize(this, type, categoryType, matchingType, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, categoryType, matchingType, tags) {
        obj['type'] = type;
        obj['category_type'] = categoryType;
        obj['matching_type'] = matchingType;
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>RuleAdditionalCategory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Vouchery/RuleAdditionalCategory} obj Optional instance to populate.
     * @return {module:Vouchery/RuleAdditionalCategory} The populated <code>RuleAdditionalCategory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleAdditionalCategory();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('category_type')) {
                obj['category_type'] = ApiClient.convertToType(data['category_type'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('matching_type')) {
                obj['matching_type'] = ApiClient.convertToType(data['matching_type'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Vouchery/RuleAdditionalCategory.TypeEnum} type
 */
RuleAdditionalCategory.prototype['type'] = undefined;

/**
 * @member {module:Vouchery/RuleAdditionalCategory.CategoryTypeEnum} category_type
 */
RuleAdditionalCategory.prototype['category_type'] = undefined;

/**
 * Name of category, rule will be related to.
 * @member {String} category
 */
RuleAdditionalCategory.prototype['category'] = undefined;

/**
 * any_of means that all products should have tags in mentioned category. none_of - products shouldn't have tags.
 * @member {module:Vouchery/RuleAdditionalCategory.MatchingTypeEnum} matching_type
 */
RuleAdditionalCategory.prototype['matching_type'] = undefined;

/**
 * @member {Array.<String>} tags
 */
RuleAdditionalCategory.prototype['tags'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
RuleAdditionalCategory['TypeEnum'] = {

    /**
     * value: "AdditionalCategory"
     * @const
     */
    "AdditionalCategory": "AdditionalCategory"
};


/**
 * Allowed values for the <code>category_type</code> property.
 * @enum {String}
 * @readonly
 */
RuleAdditionalCategory['CategoryTypeEnum'] = {

    /**
     * value: "additional"
     * @const
     */
    "additional": "additional"
};


/**
 * Allowed values for the <code>matching_type</code> property.
 * @enum {String}
 * @readonly
 */
RuleAdditionalCategory['MatchingTypeEnum'] = {

    /**
     * value: "any_of"
     * @const
     */
    "any_of": "any_of",

    /**
     * value: "none_of"
     * @const
     */
    "none_of": "none_of"
};



export default RuleAdditionalCategory;