/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RuleProductCategory model module.
 * @module Vouchery/RuleProductCategory
 * @version 2.0.0
 */
class RuleProductCategory {
    /**
     * Constructs a new <code>RuleProductCategory</code>.
     * @alias module:Vouchery/RuleProductCategory
     * @param type {module:Vouchery/RuleProductCategory.TypeEnum} 
     * @param categoryType {module:Vouchery/RuleProductCategory.CategoryTypeEnum} 
     * @param matchingType {module:Vouchery/RuleProductCategory.MatchingTypeEnum} any_of means that product should have tags in mentioned category. none_of - product shouldn't have tags.
     * @param tags {Array.<String>} 
     */
    constructor(type, categoryType, matchingType, tags) {

        RuleProductCategory.initialize(this, type, categoryType, matchingType, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, categoryType, matchingType, tags) {
        obj['type'] = type;
        obj['category_type'] = categoryType;
        obj['matching_type'] = matchingType;
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>RuleProductCategory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Vouchery/RuleProductCategory} obj Optional instance to populate.
     * @return {module:Vouchery/RuleProductCategory} The populated <code>RuleProductCategory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleProductCategory();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('category_type')) {
                obj['category_type'] = ApiClient.convertToType(data['category_type'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('matching_type')) {
                obj['matching_type'] = ApiClient.convertToType(data['matching_type'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Vouchery/RuleProductCategory.TypeEnum} type
 */
RuleProductCategory.prototype['type'] = undefined;

/**
 * @member {module:Vouchery/RuleProductCategory.CategoryTypeEnum} category_type
 */
RuleProductCategory.prototype['category_type'] = undefined;

/**
 * Name of category, rule will be related to.
 * @member {String} category
 */
RuleProductCategory.prototype['category'] = undefined;

/**
 * any_of means that product should have tags in mentioned category. none_of - product shouldn't have tags.
 * @member {module:Vouchery/RuleProductCategory.MatchingTypeEnum} matching_type
 */
RuleProductCategory.prototype['matching_type'] = undefined;

/**
 * @member {Array.<String>} tags
 */
RuleProductCategory.prototype['tags'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
RuleProductCategory['TypeEnum'] = {

    /**
     * value: "ProductCategory"
     * @const
     */
    "ProductCategory": "ProductCategory"
};


/**
 * Allowed values for the <code>category_type</code> property.
 * @enum {String}
 * @readonly
 */
RuleProductCategory['CategoryTypeEnum'] = {

    /**
     * value: "product"
     * @const
     */
    "product": "product"
};


/**
 * Allowed values for the <code>matching_type</code> property.
 * @enum {String}
 * @readonly
 */
RuleProductCategory['MatchingTypeEnum'] = {

    /**
     * value: "any_of"
     * @const
     */
    "any_of": "any_of",

    /**
     * value: "none_of"
     * @const
     */
    "none_of": "none_of"
};



export default RuleProductCategory;