/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Rule model module.
 * @module Vouchery/Rule
 * @version 2.0.0
 */
class Rule {
    /**
     * Constructs a new <code>Rule</code>.
     * @alias module:Vouchery/Rule
     * @param type {module:Vouchery/Rule.TypeEnum} 
     */
    constructor(type) {

        Rule.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) {
        obj['type'] = type;
    }

    /**
     * Constructs a <code>Rule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Vouchery/Rule} obj Optional instance to populate.
     * @return {module:Vouchery/Rule} The populated <code>Rule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Rule();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('campaign_id')) {
                obj['campaign_id'] = ApiClient.convertToType(data['campaign_id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Rule.prototype['id'] = undefined;

/**
 * @member {module:Vouchery/Rule.TypeEnum} type
 */
Rule.prototype['type'] = undefined;

/**
 * @member {Number} campaign_id
 */
Rule.prototype['campaign_id'] = undefined;

/**
 * @member {Date} created_at
 */
Rule.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Rule.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Rule['TypeEnum'] = {

    /**
     * value: "Rule"
     * @const
     */
    "Rule": "Rule"
};



export default Rule;