/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Subscription model module.
 * @module Vouchery/Subscription
 * @version 2.0.0
 */
class Subscription {
    /**
     * Constructs a new <code>Subscription</code>.
     * @alias module:Vouchery/Subscription
     * @param callbackUrl {String} 
     * @param events {Array.<module:Vouchery/Subscription.EventsEnum>} 
     */
    constructor(callbackUrl, events) {

        Subscription.initialize(this, callbackUrl, events);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, callbackUrl, events) {
        obj['callback_url'] = callbackUrl;
        obj['events'] = events;
    }

    /**
     * Constructs a <code>Subscription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Vouchery/Subscription} obj Optional instance to populate.
     * @return {module:Vouchery/Subscription} The populated <code>Subscription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Subscription();

            if (data.hasOwnProperty('callback_url')) {
                obj['callback_url'] = ApiClient.convertToType(data['callback_url'], 'String');
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], ['String']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('verification_code')) {
                obj['verification_code'] = ApiClient.convertToType(data['verification_code'], 'String');
            }
            if (data.hasOwnProperty('url_verified')) {
                obj['url_verified'] = ApiClient.convertToType(data['url_verified'], 'Boolean');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} callback_url
 */
Subscription.prototype['callback_url'] = undefined;

/**
 * @member {Array.<module:Vouchery/Subscription.EventsEnum>} events
 */
Subscription.prototype['events'] = undefined;

/**
 * @member {module:Vouchery/Subscription.TypeEnum} type
 */
Subscription.prototype['type'] = undefined;

/**
 * @member {Number} id
 */
Subscription.prototype['id'] = undefined;

/**
 * @member {Boolean} active
 */
Subscription.prototype['active'] = undefined;

/**
 * @member {String} verification_code
 */
Subscription.prototype['verification_code'] = undefined;

/**
 * @member {Boolean} url_verified
 */
Subscription.prototype['url_verified'] = undefined;

/**
 * @member {Date} created_at
 */
Subscription.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Subscription.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>events</code> property.
 * @enum {String}
 * @readonly
 */
Subscription['EventsEnum'] = {

    /**
     * value: "voucher_redeemed"
     * @const
     */
    "voucher_redeemed": "voucher_redeemed",

    /**
     * value: "voucher_batch_created"
     * @const
     */
    "voucher_batch_created": "voucher_batch_created",

    /**
     * value: "voucher_created"
     * @const
     */
    "voucher_created": "voucher_created",

    /**
     * value: "voucher_redemption_rejected"
     * @const
     */
    "voucher_redemption_rejected": "voucher_redemption_rejected",

    /**
     * value: "budget_limit_reached"
     * @const
     */
    "budget_limit_reached": "budget_limit_reached",

    /**
     * value: "voucher_redemptions_limit_reached"
     * @const
     */
    "voucher_redemptions_limit_reached": "voucher_redemptions_limit_reached",

    /**
     * value: "voucher_pool_reached"
     * @const
     */
    "voucher_pool_reached": "voucher_pool_reached"
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Subscription['TypeEnum'] = {

    /**
     * value: "Subscription"
     * @const
     */
    "Subscription": "Subscription"
};



export default Subscription;