/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Voucher model module.
 * @module Vouchery/Voucher
 * @version 2.0.0
 */
class Voucher {
    /**
     * Constructs a new <code>Voucher</code>.
     * @alias module:Vouchery/Voucher
     * @param type {module:Vouchery/Voucher.TypeEnum} 
     * @param active {Boolean} 
     * @param code {String} 
     */
    constructor(type, active, code) {

        Voucher.initialize(this, type, active, code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, active, code) {
        obj['type'] = type;
        obj['active'] = active;
        obj['code'] = code;
    }

    /**
     * Constructs a <code>Voucher</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Vouchery/Voucher} obj Optional instance to populate.
     * @return {module:Vouchery/Voucher} The populated <code>Voucher</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Voucher();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('campaign_id')) {
                obj['campaign_id'] = ApiClient.convertToType(data['campaign_id'], 'Number');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('customer_identifier')) {
                obj['customer_identifier'] = ApiClient.convertToType(data['customer_identifier'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:Vouchery/Voucher.TypeEnum} type
 */
Voucher.prototype['type'] = undefined;

/**
 * @member {Number} id
 */
Voucher.prototype['id'] = undefined;

/**
 * @member {Number} campaign_id
 */
Voucher.prototype['campaign_id'] = undefined;

/**
 * @member {Boolean} active
 */
Voucher.prototype['active'] = undefined;

/**
 * @member {module:Vouchery/Voucher.StatusEnum} status
 */
Voucher.prototype['status'] = undefined;

/**
 * @member {String} code
 */
Voucher.prototype['code'] = undefined;

/**
 * A string uniquely identifying customer in your system. Please check customers API.
 * @member {String} customer_identifier
 */
Voucher.prototype['customer_identifier'] = undefined;

/**
 * @member {Date} created_at
 */
Voucher.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Voucher.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Voucher['TypeEnum'] = {

    /**
     * value: "Voucher"
     * @const
     */
    "Voucher": "Voucher"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Voucher['StatusEnum'] = {

    /**
     * value: "created"
     * @const
     */
    "created": "created",

    /**
     * value: "distributed"
     * @const
     */
    "distributed": "distributed",

    /**
     * value: "validated"
     * @const
     */
    "validated": "validated",

    /**
     * value: "redeemed"
     * @const
     */
    "redeemed": "redeemed",

    /**
     * value: "expired"
     * @const
     */
    "expired": "expired"
};



export default Voucher;