/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Campaign from '../Vouchery/Campaign';
import MainCampaign from '../Vouchery/MainCampaign';

/**
 * Campaigns service.
 * @module api/CampaignsApi
 * @version 2.0.0
 */
export default class CampaignsApi {

    /**
     * Constructs a new CampaignsApi. 
     * @alias module:api/CampaignsApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create a campaign
     * @param {Object} opts Optional parameters
     * @param {module:Vouchery/UNKNOWN_BASE_TYPE} opts.UNKNOWN_BASE_TYPE 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Vouchery/Campaign} and HTTP response
     */
    createCampaignWithHttpInfo(opts) {
        opts = opts || {};
        let postBody = opts['UNKNOWN_BASE_TYPE'];

        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = Campaign;
        return this.apiClient.callApi(
            '/campaigns', 'POST',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Create a campaign
     * @param {Object} opts Optional parameters
     * @param {module:Vouchery/UNKNOWN_BASE_TYPE} opts.UNKNOWN_BASE_TYPE 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Vouchery/Campaign}
     */
    createCampaign(opts) {
        return this.createCampaignWithHttpInfo(opts)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


    /**
     * Delete a campaign
     * @param {Number} id Campaign ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteCampaignWithHttpInfo(id) {
        let postBody = null;
        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling deleteCampaign");
        }

        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = [];
        let accepts = [];
        let returnType = null;
        return this.apiClient.callApi(
            '/campaigns/{id}', 'DELETE',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Delete a campaign
     * @param {Number} id Campaign ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteCampaign(id) {
        return this.deleteCampaignWithHttpInfo(id)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


    /**
     * Get sub campaigns by params
     * @param {Object} opts Optional parameters
     * @param {String} opts.nameCont Name contains
     * @param {String} opts.statusEq Status
     * @param {String} opts.templateEq Template (type) of sub campaign
     * @param {String} opts.triggersOnEq Triggers On
     * @param {String} opts.triggerNameCont Trigger Name contains
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:Vouchery/Campaign>} and HTTP response
     */
    findSubCampaignsWithHttpInfo(opts) {
        opts = opts || {};
        let postBody = null;

        let pathParams = {};
        let queryParams = {
            'name_cont': opts['nameCont'],
            'status_eq': opts['statusEq'],
            'template_eq': opts['templateEq'],
            'triggers_on_eq': opts['triggersOnEq'],
            'trigger_name_cont': opts['triggerNameCont']
        };
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = [Campaign];
        return this.apiClient.callApi(
            '/campaigns/sub', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Get sub campaigns by params
     * @param {Object} opts Optional parameters
     * @param {String} opts.nameCont Name contains
     * @param {String} opts.statusEq Status
     * @param {String} opts.templateEq Template (type) of sub campaign
     * @param {String} opts.triggersOnEq Triggers On
     * @param {String} opts.triggerNameCont Trigger Name contains
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:Vouchery/Campaign>}
     */
    findSubCampaigns(opts) {
        return this.findSubCampaignsWithHttpInfo(opts)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


    /**
     * Get a campaign
     * @param {Number} id Campaign ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Vouchery/Campaign} and HTTP response
     */
    getCampaignWithHttpInfo(id) {
        let postBody = null;
        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling getCampaign");
        }

        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = Campaign;
        return this.apiClient.callApi(
            '/campaigns/{id}', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Get a campaign
     * @param {Number} id Campaign ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Vouchery/Campaign}
     */
    getCampaign(id) {
        return this.getCampaignWithHttpInfo(id)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


    /**
     * Get main campaigns with children by params
     * @param {Object} opts Optional parameters
     * @param {String} opts.nameCont Name contains
     * @param {String} opts.teamEq Team
     * @param {String} opts.statusEq Status
     * @param {String} opts.templateEq Template (promotion type) of main campaign
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:Vouchery/Campaign>} and HTTP response
     */
    getCampaignsWithHttpInfo(opts) {
        opts = opts || {};
        let postBody = null;

        let pathParams = {};
        let queryParams = {
            'name_cont': opts['nameCont'],
            'team_eq': opts['teamEq'],
            'status_eq': opts['statusEq'],
            'template_eq': opts['templateEq']
        };
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = [Campaign];
        return this.apiClient.callApi(
            '/campaigns', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Get main campaigns with children by params
     * @param {Object} opts Optional parameters
     * @param {String} opts.nameCont Name contains
     * @param {String} opts.teamEq Team
     * @param {String} opts.statusEq Status
     * @param {String} opts.templateEq Template (promotion type) of main campaign
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:Vouchery/Campaign>}
     */
    getCampaigns(opts) {
        return this.getCampaignsWithHttpInfo(opts)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


    /**
     * Get a main campaign
     * @param {Number} id Campaign ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Vouchery/MainCampaign} and HTTP response
     */
    getMainCampaignWithHttpInfo(id) {
        let postBody = null;
        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling getMainCampaign");
        }

        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = MainCampaign;
        return this.apiClient.callApi(
            '/main_campaigns/{id}', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Get a main campaign
     * @param {Number} id Campaign ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Vouchery/MainCampaign}
     */
    getMainCampaign(id) {
        return this.getMainCampaignWithHttpInfo(id)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


    /**
     * Get main campaigns with children by params
     * @param {Object} opts Optional parameters
     * @param {String} opts.nameCont Name contains
     * @param {String} opts.teamEq Teaml
     * @param {String} opts.statusEq Status
     * @param {String} opts.templateEq Template (promotion type) of main campaign
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:Vouchery/MainCampaign>} and HTTP response
     */
    getMainCampaignsWithHttpInfo(opts) {
        opts = opts || {};
        let postBody = null;

        let pathParams = {};
        let queryParams = {
            'name_cont': opts['nameCont'],
            'team_eq': opts['teamEq'],
            'status_eq': opts['statusEq'],
            'template_eq': opts['templateEq']
        };
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = [MainCampaign];
        return this.apiClient.callApi(
            '/main_campaigns', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Get main campaigns with children by params
     * @param {Object} opts Optional parameters
     * @param {String} opts.nameCont Name contains
     * @param {String} opts.teamEq Teaml
     * @param {String} opts.statusEq Status
     * @param {String} opts.templateEq Template (promotion type) of main campaign
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:Vouchery/MainCampaign>}
     */
    getMainCampaigns(opts) {
        return this.getMainCampaignsWithHttpInfo(opts)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


    /**
     * Update a campaign
     * @param {Number} id Campaign ID
     * @param {Object} opts Optional parameters
     * @param {module:Vouchery/UNKNOWN_BASE_TYPE} opts.UNKNOWN_BASE_TYPE 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Vouchery/Campaign} and HTTP response
     */
    updateCampaignWithHttpInfo(id, opts) {
        opts = opts || {};
        let postBody = opts['UNKNOWN_BASE_TYPE'];
        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling updateCampaign");
        }

        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = Campaign;
        return this.apiClient.callApi(
            '/campaigns/{id}', 'PATCH',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Update a campaign
     * @param {Number} id Campaign ID
     * @param {Object} opts Optional parameters
     * @param {module:Vouchery/UNKNOWN_BASE_TYPE} opts.UNKNOWN_BASE_TYPE 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Vouchery/Campaign}
     */
    updateCampaign(id, opts) {
        return this.updateCampaignWithHttpInfo(id, opts)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


}