/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Company from '../Vouchery/Company';

/**
 * Company service.
 * @module api/CompanyApi
 * @version 2.0.0
 */
export default class CompanyApi {

    /**
     * Constructs a new CompanyApi. 
     * @alias module:api/CompanyApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Update company details
     * @param {Object} opts Optional parameters
     * @param {module:Vouchery/Company} opts.company 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Vouchery/Company} and HTTP response
     */
    updateCompanyWithHttpInfo(opts) {
        opts = opts || {};
        let postBody = opts['company'];

        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = Company;
        return this.apiClient.callApi(
            '/company', 'PATCH',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Update company details
     * @param {Object} opts Optional parameters
     * @param {module:Vouchery/Company} opts.company 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Vouchery/Company}
     */
    updateCompany(opts) {
        return this.updateCompanyWithHttpInfo(opts)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


}