/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MaxDiscountRule from '../model/MaxDiscountRule';

/**
 * MaxDiscountRule service.
 * @module api/MaxDiscountRuleApi
 * @version 1.0
 */
export default class MaxDiscountRuleApi {

    /**
     * Constructs a new MaxDiscountRuleApi. 
     * @alias module:api/MaxDiscountRuleApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createMaxDiscountRule operation.
     * @callback module:api/MaxDiscountRuleApi~createMaxDiscountRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MaxDiscountRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create the max discount rule
     * @param {Number} campaignId Campaign ID
     * @param {Object} opts Optional parameters
     * @param {module:model/MaxDiscountRule} opts.maxDiscountRule 
     * @param {module:api/MaxDiscountRuleApi~createMaxDiscountRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MaxDiscountRule}
     */
    createMaxDiscountRule(campaignId, opts, callback) {
        opts = opts || {};
        let postBody = opts['maxDiscountRule'];

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling createMaxDiscountRule");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = MaxDiscountRule;

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/max_discount_rule', 'POST',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the deleteMaxDiscountRule operation.
     * @callback module:api/MaxDiscountRuleApi~deleteMaxDiscountRuleCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a rule
     * @param {Number} campaignId Campaign ID
     * @param {module:api/MaxDiscountRuleApi~deleteMaxDiscountRuleCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteMaxDiscountRule(campaignId, callback) {
        let postBody = null;

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling deleteMaxDiscountRule");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = [];
        let returnType = null;

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/max_discount_rule', 'DELETE',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the getMaxDiscountRule operation.
     * @callback module:api/MaxDiscountRuleApi~getMaxDiscountRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MaxDiscountRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the max discount rule
     * @param {Number} campaignId Campaign ID
     * @param {module:api/MaxDiscountRuleApi~getMaxDiscountRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MaxDiscountRule}
     */
    getMaxDiscountRule(campaignId, callback) {
        let postBody = null;

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling getMaxDiscountRule");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = MaxDiscountRule;

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/max_discount_rule', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the updateMaxDiscountRule operation.
     * @callback module:api/MaxDiscountRuleApi~updateMaxDiscountRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MaxDiscountRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the max discount rule
     * @param {Number} campaignId Campaign ID
     * @param {Object} opts Optional parameters
     * @param {module:model/MaxDiscountRule} opts.maxDiscountRule 
     * @param {module:api/MaxDiscountRuleApi~updateMaxDiscountRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MaxDiscountRule}
     */
    updateMaxDiscountRule(campaignId, opts, callback) {
        opts = opts || {};
        let postBody = opts['maxDiscountRule'];

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling updateMaxDiscountRule");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = MaxDiscountRule;

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/max_discount_rule', 'PATCH',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }


}