/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import NewCustomerRule from '../model/NewCustomerRule';

/**
 * NewCustomerRule service.
 * @module api/NewCustomerRuleApi
 * @version 1.0
 */
export default class NewCustomerRuleApi {

    /**
     * Constructs a new NewCustomerRuleApi. 
     * @alias module:api/NewCustomerRuleApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createNewCustomerRule operation.
     * @callback module:api/NewCustomerRuleApi~createNewCustomerRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NewCustomerRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create the new customer rule
     * @param {Number} campaignId Campaign ID
     * @param {Object} opts Optional parameters
     * @param {module:model/NewCustomerRule} opts.newCustomerRule 
     * @param {module:api/NewCustomerRuleApi~createNewCustomerRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NewCustomerRule}
     */
    createNewCustomerRule(campaignId, opts, callback) {
        opts = opts || {};
        let postBody = opts['newCustomerRule'];

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling createNewCustomerRule");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = NewCustomerRule;

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/new_customer_rule', 'POST',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the deleteNewCustomerRule operation.
     * @callback module:api/NewCustomerRuleApi~deleteNewCustomerRuleCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete the new customer rule
     * @param {Number} campaignId Campaign ID
     * @param {module:api/NewCustomerRuleApi~deleteNewCustomerRuleCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteNewCustomerRule(campaignId, callback) {
        let postBody = null;

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling deleteNewCustomerRule");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = [];
        let returnType = null;

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/new_customer_rule', 'DELETE',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the getNewCustomerRule operation.
     * @callback module:api/NewCustomerRuleApi~getNewCustomerRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NewCustomerRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the new customer rule
     * @param {Number} campaignId Campaign ID
     * @param {module:api/NewCustomerRuleApi~getNewCustomerRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NewCustomerRule}
     */
    getNewCustomerRule(campaignId, callback) {
        let postBody = null;

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling getNewCustomerRule");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = NewCustomerRule;

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/new_customer_rule', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the updateNewCustomerRule operation.
     * @callback module:api/NewCustomerRuleApi~updateNewCustomerRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NewCustomerRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the new customer rule
     * @param {Number} campaignId Campaign ID
     * @param {Object} opts Optional parameters
     * @param {module:model/NewCustomerRule} opts.newCustomerRule 
     * @param {module:api/NewCustomerRuleApi~updateNewCustomerRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NewCustomerRule}
     */
    updateNewCustomerRule(campaignId, opts, callback) {
        opts = opts || {};
        let postBody = opts['newCustomerRule'];

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling updateNewCustomerRule");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = NewCustomerRule;

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/new_customer_rule', 'PATCH',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }


}