/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AnyOfRewardGenerateVoucherRewardSetDiscountRewardSetDiscountPerItemRewardGenerateProductItemRewardAddPointsRewardAssignVoucher from '../model/AnyOfRewardGenerateVoucherRewardSetDiscountRewardSetDiscountPerItemRewardGenerateProductItemRewardAddPointsRewardAssignVoucher';
import Reward from '../model/Reward';
import UNKNOWN_BASE_TYPE from '../model/UNKNOWN_BASE_TYPE';

/**
 * Rewards service.
 * @module api/RewardsApi
 * @version 2.0
 */
export default class RewardsApi {

    /**
     * Constructs a new RewardsApi. 
     * @alias module:api/RewardsApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createReward operation.
     * @callback module:api/RewardsApi~createRewardCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Reward} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a reward
     * @param {Number} campaignId Campaign ID
     * @param {Object} opts Optional parameters
     * @param {module:model/UNKNOWN_BASE_TYPE} opts.UNKNOWN_BASE_TYPE 
     * @param {module:api/RewardsApi~createRewardCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Reward}
     */
    createReward(campaignId, opts, callback) {
        opts = opts || {};
        let postBody = opts['UNKNOWN_BASE_TYPE'];
        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling createReward");
        }

        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = Reward;
        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/rewards', 'POST',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }

    /**
     * Callback function to receive the result of the deleteReward operation.
     * @callback module:api/RewardsApi~deleteRewardCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a reward
     * @param {Number} id Reward ID
     * @param {module:api/RewardsApi~deleteRewardCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteReward(id, callback) {
        let postBody = null;
        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling deleteReward");
        }

        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = [];
        let returnType = null;
        return this.apiClient.callApi(
            '/rewards/{id}', 'DELETE',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }

    /**
     * Callback function to receive the result of the getReward operation.
     * @callback module:api/RewardsApi~getRewardCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Reward} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a reward
     * @param {Number} id Reward ID
     * @param {module:api/RewardsApi~getRewardCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Reward}
     */
    getReward(id, callback) {
        let postBody = null;
        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling getReward");
        }

        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = Reward;
        return this.apiClient.callApi(
            '/rewards/{id}', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }

    /**
     * Callback function to receive the result of the getRewards operation.
     * @callback module:api/RewardsApi~getRewardsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Reward>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all rewards for a campaign
     * @param {Number} campaignId Campaign ID
     * @param {module:api/RewardsApi~getRewardsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Reward>}
     */
    getRewards(campaignId, callback) {
        let postBody = null;
        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling getRewards");
        }

        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = [Reward];
        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/rewards', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }

    /**
     * Callback function to receive the result of the updateReward operation.
     * @callback module:api/RewardsApi~updateRewardCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Reward} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a reward
     * @param {Number} id Reward ID
     * @param {Object} opts Optional parameters
     * @param {module:model/UNKNOWN_BASE_TYPE} opts.UNKNOWN_BASE_TYPE 
     * @param {module:api/RewardsApi~updateRewardCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Reward}
     */
    updateReward(id, opts, callback) {
        opts = opts || {};
        let postBody = opts['UNKNOWN_BASE_TYPE'];
        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling updateReward");
        }

        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = Reward;
        return this.apiClient.callApi(
            '/rewards/{id}', 'PATCH',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }


}