/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Subscription from '../Vouchery/Subscription';

/**
 * Subscriptions service.
 * @module api/SubscriptionsApi
 * @version 2.0.0
 */
export default class SubscriptionsApi {

    /**
     * Constructs a new SubscriptionsApi. 
     * @alias module:api/SubscriptionsApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create a subscription
     * @param {Object} opts Optional parameters
     * @param {module:Vouchery/Subscription} opts.subscription 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Vouchery/Subscription} and HTTP response
     */
    createSubscriptionWithHttpInfo(opts) {
        opts = opts || {};
        let postBody = opts['subscription'];

        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = Subscription;
        return this.apiClient.callApi(
            '/subscriptions', 'POST',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Create a subscription
     * @param {Object} opts Optional parameters
     * @param {module:Vouchery/Subscription} opts.subscription 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Vouchery/Subscription}
     */
    createSubscription(opts) {
        return this.createSubscriptionWithHttpInfo(opts)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


    /**
     * Delete a subscription
     * @param {Number} id Subscription ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteSubscriptionWithHttpInfo(id) {
        let postBody = null;
        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling deleteSubscription");
        }

        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = [];
        let accepts = [];
        let returnType = null;
        return this.apiClient.callApi(
            '/subscriptions/{id}', 'DELETE',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Delete a subscription
     * @param {Number} id Subscription ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteSubscription(id) {
        return this.deleteSubscriptionWithHttpInfo(id)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


    /**
     * Get all subscriptions for a project
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:Vouchery/Subscription>} and HTTP response
     */
    getSubscriptionsWithHttpInfo() {
        let postBody = null;

        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = [Subscription];
        return this.apiClient.callApi(
            '/subscriptions', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Get all subscriptions for a project
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:Vouchery/Subscription>}
     */
    getSubscriptions() {
        return this.getSubscriptionsWithHttpInfo()
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


    /**
     * Verify subscription callback URL
     * @param {Number} id Subscription ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    verifySubscriptionWithHttpInfo(id) {
        let postBody = null;
        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling verifySubscription");
        }

        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Bearer'];
        let contentTypes = [];
        let accepts = [];
        let returnType = null;
        return this.apiClient.callApi(
            '/subscriptions/{id}/verify', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * Verify subscription callback URL
     * @param {Number} id Subscription ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    verifySubscription(id) {
        return this.verifySubscriptionWithHttpInfo(id)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


}