/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import TimeOfOrderRule from '../model/TimeOfOrderRule';

/**
 * TimeOfOrderRules service.
 * @module api/TimeOfOrderRulesApi
 * @version 1.0
 */
export default class TimeOfOrderRulesApi {

    /**
     * Constructs a new TimeOfOrderRulesApi. 
     * @alias module:api/TimeOfOrderRulesApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createTimeOfOrderRule operation.
     * @callback module:api/TimeOfOrderRulesApi~createTimeOfOrderRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TimeOfOrderRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a time of order rule
     * @param {Number} campaignId Campaign ID
     * @param {Object} opts Optional parameters
     * @param {module:model/TimeOfOrderRule} opts.timeOfOrderRule 
     * @param {module:api/TimeOfOrderRulesApi~createTimeOfOrderRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TimeOfOrderRule}
     */
    createTimeOfOrderRule(campaignId, opts, callback) {
        opts = opts || {};
        let postBody = opts['timeOfOrderRule'];

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling createTimeOfOrderRule");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = TimeOfOrderRule;

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/time_of_order_rules', 'POST',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the deleteTimeOfOrderRule operation.
     * @callback module:api/TimeOfOrderRulesApi~deleteTimeOfOrderRuleCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a time of order rule
     * @param {Number} id Rule ID
     * @param {module:api/TimeOfOrderRulesApi~deleteTimeOfOrderRuleCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTimeOfOrderRule(id, callback) {
        let postBody = null;

        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling deleteTimeOfOrderRule");
        }


        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = [];
        let returnType = null;

        return this.apiClient.callApi(
            '/time_of_order_rules/{id}', 'DELETE',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the getTimeOfOrderRule operation.
     * @callback module:api/TimeOfOrderRulesApi~getTimeOfOrderRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TimeOfOrderRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a time of order rule
     * @param {Number} id Time of order rule ID
     * @param {module:api/TimeOfOrderRulesApi~getTimeOfOrderRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TimeOfOrderRule}
     */
    getTimeOfOrderRule(id, callback) {
        let postBody = null;

        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling getTimeOfOrderRule");
        }


        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = TimeOfOrderRule;

        return this.apiClient.callApi(
            '/time_of_order_rules/{id}', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the getTimeOfOrderRules operation.
     * @callback module:api/TimeOfOrderRulesApi~getTimeOfOrderRulesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TimeOfOrderRule>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all time of order rules for a campaign
     * @param {Number} campaignId Campaign ID
     * @param {module:api/TimeOfOrderRulesApi~getTimeOfOrderRulesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TimeOfOrderRule>}
     */
    getTimeOfOrderRules(campaignId, callback) {
        let postBody = null;

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling getTimeOfOrderRules");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = [TimeOfOrderRule];

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/time_of_order_rules', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the updateTimeOfOrderRule operation.
     * @callback module:api/TimeOfOrderRulesApi~updateTimeOfOrderRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TimeOfOrderRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a time of order rule
     * @param {Number} id Rule ID
     * @param {Object} opts Optional parameters
     * @param {module:model/TimeOfOrderRule} opts.timeOfOrderRule 
     * @param {module:api/TimeOfOrderRulesApi~updateTimeOfOrderRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TimeOfOrderRule}
     */
    updateTimeOfOrderRule(id, opts, callback) {
        opts = opts || {};
        let postBody = opts['timeOfOrderRule'];

        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling updateTimeOfOrderRule");
        }


        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = TimeOfOrderRule;

        return this.apiClient.callApi(
            '/time_of_order_rules/{id}', 'PATCH',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }


}