/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import TimeframeRule from '../model/TimeframeRule';

/**
 * TimeframeRules service.
 * @module api/TimeframeRulesApi
 * @version 1.0
 */
export default class TimeframeRulesApi {

    /**
     * Constructs a new TimeframeRulesApi. 
     * @alias module:api/TimeframeRulesApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createTimeframeRule operation.
     * @callback module:api/TimeframeRulesApi~createTimeframeRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TimeframeRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a timeframe rule
     * @param {Number} campaignId Campaign ID
     * @param {Object} opts Optional parameters
     * @param {module:model/TimeframeRule} opts.timeframeRule 
     * @param {module:api/TimeframeRulesApi~createTimeframeRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TimeframeRule}
     */
    createTimeframeRule(campaignId, opts, callback) {
        opts = opts || {};
        let postBody = opts['timeframeRule'];

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling createTimeframeRule");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = TimeframeRule;

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/timeframe_rules', 'POST',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the deleteTimeframeRule operation.
     * @callback module:api/TimeframeRulesApi~deleteTimeframeRuleCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a timeframe rule
     * @param {Number} id Rule ID
     * @param {module:api/TimeframeRulesApi~deleteTimeframeRuleCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTimeframeRule(id, callback) {
        let postBody = null;

        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling deleteTimeframeRule");
        }


        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = [];
        let returnType = null;

        return this.apiClient.callApi(
            '/timeframe_rules/{id}', 'DELETE',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the getTimeframeRule operation.
     * @callback module:api/TimeframeRulesApi~getTimeframeRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TimeframeRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a timeframe rule
     * @param {Number} id Rule ID
     * @param {module:api/TimeframeRulesApi~getTimeframeRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TimeframeRule}
     */
    getTimeframeRule(id, callback) {
        let postBody = null;

        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling getTimeframeRule");
        }


        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = TimeframeRule;

        return this.apiClient.callApi(
            '/timeframe_rules/{id}', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the getTimeframeRules operation.
     * @callback module:api/TimeframeRulesApi~getTimeframeRulesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TimeframeRule>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all timeframe rules for a campaign
     * @param {Number} campaignId Campaign ID
     * @param {module:api/TimeframeRulesApi~getTimeframeRulesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TimeframeRule>}
     */
    getTimeframeRules(campaignId, callback) {
        let postBody = null;

        // verify the required parameter 'campaignId' is set
        if (campaignId === undefined || campaignId === null) {
            throw new Error("Missing the required parameter 'campaignId' when calling getTimeframeRules");
        }


        let pathParams = {
            'campaign_id': campaignId
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = [TimeframeRule];

        return this.apiClient.callApi(
            '/campaigns/{campaign_id}/timeframe_rules', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }

    /**
     * Callback function to receive the result of the updateTimeframeRule operation.
     * @callback module:api/TimeframeRulesApi~updateTimeframeRuleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TimeframeRule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a timeframe rule
     * @param {Number} id Rule ID
     * @param {Object} opts Optional parameters
     * @param {module:model/TimeframeRule} opts.timeframeRule 
     * @param {module:api/TimeframeRulesApi~updateTimeframeRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TimeframeRule}
     */
    updateTimeframeRule(id, opts, callback) {
        opts = opts || {};
        let postBody = opts['timeframeRule'];

        // verify the required parameter 'id' is set
        if (id === undefined || id === null) {
            throw new Error("Missing the required parameter 'id' when calling updateTimeframeRule");
        }


        let pathParams = {
            'id': id
        };
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = TimeframeRule;

        return this.apiClient.callApi(
            '/timeframe_rules/{id}', 'PATCH',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, callback
        );
    }


}