/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Trigger from '../model/Trigger';

/**
 * Triggers service.
 * @module api/TriggersApi
 * @version 2.0.0
 */
export default class TriggersApi {

    /**
     * Constructs a new TriggersApi. 
     * @alias module:api/TriggersApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createTrigger operation.
     * @callback module:api/TriggersApi~createTriggerCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Trigger} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a trigger
     * @param {Object} opts Optional parameters
     * @param {module:model/Trigger} opts.trigger 
     * @param {module:api/TriggersApi~createTriggerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Trigger}
     */
    createTrigger(opts, callback) {
        opts = opts || {};
        let postBody = opts['trigger'];

        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['Basic'];
        let contentTypes = ['application/json'];
        let accepts = ['application/json'];
        let returnType = Trigger;
        return this.apiClient.callApi(
            '/triggers', 'POST',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
        );
    }


}