/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', '../../src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.VoucheryApiReference);
    }
}(this, function(expect, VoucheryApiReference) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new VoucheryApiReference.ErrorErrors();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('ErrorErrors', function() {
        it('should create an instance of ErrorErrors', function() {
            // uncomment below and update the code to test ErrorErrors
            //var instane = new VoucheryApiReference.ErrorErrors();
            //expect(instance).to.be.a(VoucheryApiReference.ErrorErrors);
        });

        it('should have the property attribute (base name: "attribute")', function() {
            // uncomment below and update the code to test the property attribute
            //var instane = new VoucheryApiReference.ErrorErrors();
            //expect(instance).to.be();
        });

        it('should have the property code (base name: "code")', function() {
            // uncomment below and update the code to test the property code
            //var instane = new VoucheryApiReference.ErrorErrors();
            //expect(instance).to.be();
        });

        it('should have the property message (base name: "message")', function() {
            // uncomment below and update the code to test the property message
            //var instane = new VoucheryApiReference.ErrorErrors();
            //expect(instance).to.be();
        });

        it('should have the property boundaryValue (base name: "boundary_value")', function() {
            // uncomment below and update the code to test the property boundaryValue
            //var instane = new VoucheryApiReference.ErrorErrors();
            //expect(instance).to.be();
        });

    });

}));