/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VoucheryApi);
  }
}(this, function(expect, VoucheryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VoucheryApi.MainCampaign();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MainCampaign', function() {
    it('should create an instance of MainCampaign', function() {
      // uncomment below and update the code to test MainCampaign
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be.a(VoucheryApi.MainCampaign);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property template (base name: "template")', function() {
      // uncomment below and update the code to test the property template
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property maxTotalBudget (base name: "max_total_budget")', function() {
      // uncomment below and update the code to test the property maxTotalBudget
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property maxRedemptions (base name: "max_redemptions")', function() {
      // uncomment below and update the code to test the property maxRedemptions
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property team (base name: "team")', function() {
      // uncomment below and update the code to test the property team
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property budgetCode (base name: "budget_code")', function() {
      // uncomment below and update the code to test the property budgetCode
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property children (base name: "children")', function() {
      // uncomment below and update the code to test the property children
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "created_by")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

    it('should have the property updatedBy (base name: "updated_by")', function() {
      // uncomment below and update the code to test the property updatedBy
      //var instane = new VoucheryApi.MainCampaign();
      //expect(instance).to.be();
    });

  });

}));
