/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', '../../src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.VoucheryApiReference);
    }
}(this, function(expect, VoucheryApiReference) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new VoucheryApiReference.Redemption();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('Redemption', function() {
        it('should create an instance of Redemption', function() {
            // uncomment below and update the code to test Redemption
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be.a(VoucheryApiReference.Redemption);
        });

        it('should have the property type (base name: "type")', function() {
            // uncomment below and update the code to test the property type
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property transactionId (base name: "transaction_id")', function() {
            // uncomment below and update the code to test the property transactionId
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property customerIdentifier (base name: "customer_identifier")', function() {
            // uncomment below and update the code to test the property customerIdentifier
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property customer (base name: "customer")', function() {
            // uncomment below and update the code to test the property customer
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property totalTransactionCost (base name: "total_transaction_cost")', function() {
            // uncomment below and update the code to test the property totalTransactionCost
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property grantedDiscount (base name: "granted_discount")', function() {
            // uncomment below and update the code to test the property grantedDiscount
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property userAgent (base name: "user_agent")', function() {
            // uncomment below and update the code to test the property userAgent
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property voucher (base name: "voucher")', function() {
            // uncomment below and update the code to test the property voucher
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property location (base name: "location")', function() {
            // uncomment below and update the code to test the property location
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property categories (base name: "categories")', function() {
            // uncomment below and update the code to test the property categories
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property confirmed (base name: "confirmed")', function() {
            // uncomment below and update the code to test the property confirmed
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property validatedAt (base name: "validated_at")', function() {
            // uncomment below and update the code to test the property validatedAt
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property confirmedAt (base name: "confirmed_at")', function() {
            // uncomment below and update the code to test the property confirmedAt
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property createdAt (base name: "created_at")', function() {
            // uncomment below and update the code to test the property createdAt
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

        it('should have the property updatedAt (base name: "updated_at")', function() {
            // uncomment below and update the code to test the property updatedAt
            //var instane = new VoucheryApiReference.Redemption();
            //expect(instance).to.be();
        });

    });

}));