/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VoucheryApi);
  }
}(this, function(expect, VoucheryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VoucheryApi.RewardSetDiscountPerItemItemConditions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RewardSetDiscountPerItemItemConditions', function() {
    it('should create an instance of RewardSetDiscountPerItemItemConditions', function() {
      // uncomment below and update the code to test RewardSetDiscountPerItemItemConditions
      //var instane = new VoucheryApi.RewardSetDiscountPerItemItemConditions();
      //expect(instance).to.be.a(VoucheryApi.RewardSetDiscountPerItemItemConditions);
    });

    it('should have the property field (base name: "field")', function() {
      // uncomment below and update the code to test the property field
      //var instane = new VoucheryApi.RewardSetDiscountPerItemItemConditions();
      //expect(instance).to.be();
    });

    it('should have the property operator (base name: "operator")', function() {
      // uncomment below and update the code to test the property operator
      //var instane = new VoucheryApi.RewardSetDiscountPerItemItemConditions();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instane = new VoucheryApi.RewardSetDiscountPerItemItemConditions();
      //expect(instance).to.be();
    });

    it('should have the property logicalBinding (base name: "logical_binding")', function() {
      // uncomment below and update the code to test the property logicalBinding
      //var instane = new VoucheryApi.RewardSetDiscountPerItemItemConditions();
      //expect(instance).to.be();
    });

  });

}));
