/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VoucheryApi);
  }
}(this, function(expect, VoucheryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VoucheryApi.SubCampaign();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubCampaign', function() {
    it('should create an instance of SubCampaign', function() {
      // uncomment below and update the code to test SubCampaign
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be.a(VoucheryApi.SubCampaign);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property parentId (base name: "parent_id")', function() {
      // uncomment below and update the code to test the property parentId
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property triggersOn (base name: "triggers_on")', function() {
      // uncomment below and update the code to test the property triggersOn
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property triggerName (base name: "trigger_name")', function() {
      // uncomment below and update the code to test the property triggerName
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property template (base name: "template")', function() {
      // uncomment below and update the code to test the property template
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property customerInformation (base name: "customer_information")', function() {
      // uncomment below and update the code to test the property customerInformation
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property maxTotalBudget (base name: "max_total_budget")', function() {
      // uncomment below and update the code to test the property maxTotalBudget
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property maxRedemptions (base name: "max_redemptions")', function() {
      // uncomment below and update the code to test the property maxRedemptions
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property minimumValue (base name: "minimum_value")', function() {
      // uncomment below and update the code to test the property minimumValue
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property maxDiscount (base name: "max_discount")', function() {
      // uncomment below and update the code to test the property maxDiscount
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property redemptionsCount (base name: "redemptions_count")', function() {
      // uncomment below and update the code to test the property redemptionsCount
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property totalBudgetSpent (base name: "total_budget_spent")', function() {
      // uncomment below and update the code to test the property totalBudgetSpent
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property vouchersDistributedCount (base name: "vouchers_distributed_count")', function() {
      // uncomment below and update the code to test the property vouchersDistributedCount
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property vouchersCount (base name: "vouchers_count")', function() {
      // uncomment below and update the code to test the property vouchersCount
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property currencySymbol (base name: "currency_symbol")', function() {
      // uncomment below and update the code to test the property currencySymbol
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property channel (base name: "channel")', function() {
      // uncomment below and update the code to test the property channel
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property purpose (base name: "purpose")', function() {
      // uncomment below and update the code to test the property purpose
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property medium (base name: "medium")', function() {
      // uncomment below and update the code to test the property medium
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property voucherType (base name: "voucher_type")', function() {
      // uncomment below and update the code to test the property voucherType
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property voucherMaxRedemptions (base name: "voucher_max_redemptions")', function() {
      // uncomment below and update the code to test the property voucherMaxRedemptions
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property voucherCodeType (base name: "voucher_code_type")', function() {
      // uncomment below and update the code to test the property voucherCodeType
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property voucherRandomPartLength (base name: "voucher_random_part_length")', function() {
      // uncomment below and update the code to test the property voucherRandomPartLength
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property voucherPrefix (base name: "voucher_prefix")', function() {
      // uncomment below and update the code to test the property voucherPrefix
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "created_by")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

    it('should have the property updatedBy (base name: "updated_by")', function() {
      // uncomment below and update the code to test the property updatedBy
      //var instane = new VoucheryApi.SubCampaign();
      //expect(instance).to.be();
    });

  });

}));
