/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Batch from './model/Batch';
import Campaign from './model/Campaign';
import Category from './model/Category';
import Customer from './model/Customer';
import CustomerCategories from './model/CustomerCategories';
import Error from './model/Error';
import ErrorErrors from './model/ErrorErrors';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InlineObject2 from './model/InlineObject2';
import InlineObject3 from './model/InlineObject3';
import InlineObject4 from './model/InlineObject4';
import InlineResponse200 from './model/InlineResponse200';
import Redemption from './model/Redemption';
import RedemptionProductItems from './model/RedemptionProductItems';
import RedemptionVoucher from './model/RedemptionVoucher';
import Reward from './model/Reward';
import RewardAddPoints from './model/RewardAddPoints';
import RewardAssignVoucher from './model/RewardAssignVoucher';
import RewardGenerateProductItem from './model/RewardGenerateProductItem';
import RewardGenerateVoucher from './model/RewardGenerateVoucher';
import RewardSetDiscount from './model/RewardSetDiscount';
import RewardSetDiscountPerItem from './model/RewardSetDiscountPerItem';
import Rule from './model/Rule';
import RuleCustomerCategory from './model/RuleCustomerCategory';
import RuleCustomerMaxRedemptions from './model/RuleCustomerMaxRedemptions';
import RuleCustomerPoints from './model/RuleCustomerPoints';
import RuleProductItemExists from './model/RuleProductItemExists';
import RuleProductItemExistsItemConditions from './model/RuleProductItemExistsItemConditions';
import RuleTimeOfOrder from './model/RuleTimeOfOrder';
import RuleTimeframe from './model/RuleTimeframe';
import RuleTriggersAmount from './model/RuleTriggersAmount';
import Trigger from './model/Trigger';
import User from './model/User';
import Voucher from './model/Voucher';
import CampaignsApi from './api/CampaignsApi';
import CategoriesApi from './api/CategoriesApi';
import CustomersApi from './api/CustomersApi';
import RedemptionsApi from './api/RedemptionsApi';
import RewardsApi from './api/RewardsApi';
import RulesApi from './api/RulesApi';
import TriggersApi from './api/TriggersApi';
import UsersApi from './api/UsersApi';
import VouchersApi from './api/VouchersApi';


/**
 * JS API client generated by OpenAPI Generator.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var VoucheryApi = require('index'); // See note below*.
 * var xxxSvc = new VoucheryApi.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new VoucheryApi.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new VoucheryApi.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new VoucheryApi.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version 2.0
 */
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Batch model constructor.
     * @property {module:model/Batch}
     */
    Batch,

    /**
     * The Campaign model constructor.
     * @property {module:model/Campaign}
     */
    Campaign,

    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category,

    /**
     * The Customer model constructor.
     * @property {module:model/Customer}
     */
    Customer,

    /**
     * The CustomerCategories model constructor.
     * @property {module:model/CustomerCategories}
     */
    CustomerCategories,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ErrorErrors model constructor.
     * @property {module:model/ErrorErrors}
     */
    ErrorErrors,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject2 model constructor.
     * @property {module:model/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject3 model constructor.
     * @property {module:model/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineObject4 model constructor.
     * @property {module:model/InlineObject4}
     */
    InlineObject4,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The Redemption model constructor.
     * @property {module:model/Redemption}
     */
    Redemption,

    /**
     * The RedemptionProductItems model constructor.
     * @property {module:model/RedemptionProductItems}
     */
    RedemptionProductItems,

    /**
     * The RedemptionVoucher model constructor.
     * @property {module:model/RedemptionVoucher}
     */
    RedemptionVoucher,

    /**
     * The Reward model constructor.
     * @property {module:model/Reward}
     */
    Reward,

    /**
     * The RewardAddPoints model constructor.
     * @property {module:model/RewardAddPoints}
     */
    RewardAddPoints,

    /**
     * The RewardAssignVoucher model constructor.
     * @property {module:model/RewardAssignVoucher}
     */
    RewardAssignVoucher,

    /**
     * The RewardGenerateProductItem model constructor.
     * @property {module:model/RewardGenerateProductItem}
     */
    RewardGenerateProductItem,

    /**
     * The RewardGenerateVoucher model constructor.
     * @property {module:model/RewardGenerateVoucher}
     */
    RewardGenerateVoucher,

    /**
     * The RewardSetDiscount model constructor.
     * @property {module:model/RewardSetDiscount}
     */
    RewardSetDiscount,

    /**
     * The RewardSetDiscountPerItem model constructor.
     * @property {module:model/RewardSetDiscountPerItem}
     */
    RewardSetDiscountPerItem,

    /**
     * The Rule model constructor.
     * @property {module:model/Rule}
     */
    Rule,

    /**
     * The RuleCustomerCategory model constructor.
     * @property {module:model/RuleCustomerCategory}
     */
    RuleCustomerCategory,

    /**
     * The RuleCustomerMaxRedemptions model constructor.
     * @property {module:model/RuleCustomerMaxRedemptions}
     */
    RuleCustomerMaxRedemptions,

    /**
     * The RuleCustomerPoints model constructor.
     * @property {module:model/RuleCustomerPoints}
     */
    RuleCustomerPoints,

    /**
     * The RuleProductItemExists model constructor.
     * @property {module:model/RuleProductItemExists}
     */
    RuleProductItemExists,

    /**
     * The RuleProductItemExistsItemConditions model constructor.
     * @property {module:model/RuleProductItemExistsItemConditions}
     */
    RuleProductItemExistsItemConditions,

    /**
     * The RuleTimeOfOrder model constructor.
     * @property {module:model/RuleTimeOfOrder}
     */
    RuleTimeOfOrder,

    /**
     * The RuleTimeframe model constructor.
     * @property {module:model/RuleTimeframe}
     */
    RuleTimeframe,

    /**
     * The RuleTriggersAmount model constructor.
     * @property {module:model/RuleTriggersAmount}
     */
    RuleTriggersAmount,

    /**
     * The Trigger model constructor.
     * @property {module:model/Trigger}
     */
    Trigger,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The Voucher model constructor.
     * @property {module:model/Voucher}
     */
    Voucher,

    /**
     * The CampaignsApi service constructor.
     * @property {module:api/CampaignsApi}
     */
    CampaignsApi,

    /**
     * The CategoriesApi service constructor.
     * @property {module:api/CategoriesApi}
     */
    CategoriesApi,

    /**
     * The CustomersApi service constructor.
     * @property {module:api/CustomersApi}
     */
    CustomersApi,

    /**
     * The RedemptionsApi service constructor.
     * @property {module:api/RedemptionsApi}
     */
    RedemptionsApi,

    /**
     * The RewardsApi service constructor.
     * @property {module:api/RewardsApi}
     */
    RewardsApi,

    /**
     * The RulesApi service constructor.
     * @property {module:api/RulesApi}
     */
    RulesApi,

    /**
     * The TriggersApi service constructor.
     * @property {module:api/TriggersApi}
     */
    TriggersApi,

    /**
     * The UsersApi service constructor.
     * @property {module:api/UsersApi}
     */
    UsersApi,

    /**
     * The VouchersApi service constructor.
     * @property {module:api/VouchersApi}
     */
    VouchersApi
};