/**
 * Vouchery API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Batch from './Vouchery/Batch';
import Campaign from './Vouchery/Campaign';
import Category from './Vouchery/Category';
import Customer from './Vouchery/Customer';
import CustomerCategories from './Vouchery/CustomerCategories';
import Error from './Vouchery/Error';
import ErrorErrors from './Vouchery/ErrorErrors';
import InlineObject from './Vouchery/InlineObject';
import InlineObject1 from './Vouchery/InlineObject1';
import InlineObject2 from './Vouchery/InlineObject2';
import InlineObject3 from './Vouchery/InlineObject3';
import InlineObject4 from './Vouchery/InlineObject4';
import InlineResponse200 from './Vouchery/InlineResponse200';
import Redemption from './Vouchery/Redemption';
import RedemptionProductItems from './Vouchery/RedemptionProductItems';
import RedemptionVoucher from './Vouchery/RedemptionVoucher';
import Reward from './Vouchery/Reward';
import RewardAddPoints from './Vouchery/RewardAddPoints';
import RewardAssignVoucher from './Vouchery/RewardAssignVoucher';
import RewardGenerateProductItem from './Vouchery/RewardGenerateProductItem';
import RewardGenerateVoucher from './Vouchery/RewardGenerateVoucher';
import RewardSetDiscount from './Vouchery/RewardSetDiscount';
import RewardSetDiscountPerItem from './Vouchery/RewardSetDiscountPerItem';
import Rule from './Vouchery/Rule';
import RuleCustomerCategory from './Vouchery/RuleCustomerCategory';
import RuleCustomerMaxRedemptions from './Vouchery/RuleCustomerMaxRedemptions';
import RuleCustomerPoints from './Vouchery/RuleCustomerPoints';
import RuleProductItemExists from './Vouchery/RuleProductItemExists';
import RuleProductItemExistsItemConditions from './Vouchery/RuleProductItemExistsItemConditions';
import RuleTimeOfOrder from './Vouchery/RuleTimeOfOrder';
import RuleTimeframe from './Vouchery/RuleTimeframe';
import RuleTriggersAmount from './Vouchery/RuleTriggersAmount';
import Trigger from './Vouchery/Trigger';
import User from './Vouchery/User';
import Voucher from './Vouchery/Voucher';
import CampaignsApi from './api/CampaignsApi';
import CategoriesApi from './api/CategoriesApi';
import CustomersApi from './api/CustomersApi';
import RedemptionsApi from './api/RedemptionsApi';
import RewardsApi from './api/RewardsApi';
import RulesApi from './api/RulesApi';
import TriggersApi from './api/TriggersApi';
import UsersApi from './api/UsersApi';
import VouchersApi from './api/VouchersApi';


/**
 * JS API client generated by OpenAPI Generator.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var VoucheryApi = require('index'); // See note below*.
 * var xxxSvc = new VoucheryApi.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new VoucheryApi.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new VoucheryApi.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new VoucheryApi.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version 2.0.0
 */
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Batch model constructor.
     * @property {module:Vouchery/Batch}
     */
    Batch,

    /**
     * The Campaign model constructor.
     * @property {module:Vouchery/Campaign}
     */
    Campaign,

    /**
     * The Category model constructor.
     * @property {module:Vouchery/Category}
     */
    Category,

    /**
     * The Customer model constructor.
     * @property {module:Vouchery/Customer}
     */
    Customer,

    /**
     * The CustomerCategories model constructor.
     * @property {module:Vouchery/CustomerCategories}
     */
    CustomerCategories,

    /**
     * The Error model constructor.
     * @property {module:Vouchery/Error}
     */
    Error,

    /**
     * The ErrorErrors model constructor.
     * @property {module:Vouchery/ErrorErrors}
     */
    ErrorErrors,

    /**
     * The InlineObject model constructor.
     * @property {module:Vouchery/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:Vouchery/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject2 model constructor.
     * @property {module:Vouchery/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject3 model constructor.
     * @property {module:Vouchery/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineObject4 model constructor.
     * @property {module:Vouchery/InlineObject4}
     */
    InlineObject4,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:Vouchery/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The Redemption model constructor.
     * @property {module:Vouchery/Redemption}
     */
    Redemption,

    /**
     * The RedemptionProductItems model constructor.
     * @property {module:Vouchery/RedemptionProductItems}
     */
    RedemptionProductItems,

    /**
     * The RedemptionVoucher model constructor.
     * @property {module:Vouchery/RedemptionVoucher}
     */
    RedemptionVoucher,

    /**
     * The Reward model constructor.
     * @property {module:Vouchery/Reward}
     */
    Reward,

    /**
     * The RewardAddPoints model constructor.
     * @property {module:Vouchery/RewardAddPoints}
     */
    RewardAddPoints,

    /**
     * The RewardAssignVoucher model constructor.
     * @property {module:Vouchery/RewardAssignVoucher}
     */
    RewardAssignVoucher,

    /**
     * The RewardGenerateProductItem model constructor.
     * @property {module:Vouchery/RewardGenerateProductItem}
     */
    RewardGenerateProductItem,

    /**
     * The RewardGenerateVoucher model constructor.
     * @property {module:Vouchery/RewardGenerateVoucher}
     */
    RewardGenerateVoucher,

    /**
     * The RewardSetDiscount model constructor.
     * @property {module:Vouchery/RewardSetDiscount}
     */
    RewardSetDiscount,

    /**
     * The RewardSetDiscountPerItem model constructor.
     * @property {module:Vouchery/RewardSetDiscountPerItem}
     */
    RewardSetDiscountPerItem,

    /**
     * The Rule model constructor.
     * @property {module:Vouchery/Rule}
     */
    Rule,

    /**
     * The RuleCustomerCategory model constructor.
     * @property {module:Vouchery/RuleCustomerCategory}
     */
    RuleCustomerCategory,

    /**
     * The RuleCustomerMaxRedemptions model constructor.
     * @property {module:Vouchery/RuleCustomerMaxRedemptions}
     */
    RuleCustomerMaxRedemptions,

    /**
     * The RuleCustomerPoints model constructor.
     * @property {module:Vouchery/RuleCustomerPoints}
     */
    RuleCustomerPoints,

    /**
     * The RuleProductItemExists model constructor.
     * @property {module:Vouchery/RuleProductItemExists}
     */
    RuleProductItemExists,

    /**
     * The RuleProductItemExistsItemConditions model constructor.
     * @property {module:Vouchery/RuleProductItemExistsItemConditions}
     */
    RuleProductItemExistsItemConditions,

    /**
     * The RuleTimeOfOrder model constructor.
     * @property {module:Vouchery/RuleTimeOfOrder}
     */
    RuleTimeOfOrder,

    /**
     * The RuleTimeframe model constructor.
     * @property {module:Vouchery/RuleTimeframe}
     */
    RuleTimeframe,

    /**
     * The RuleTriggersAmount model constructor.
     * @property {module:Vouchery/RuleTriggersAmount}
     */
    RuleTriggersAmount,

    /**
     * The Trigger model constructor.
     * @property {module:Vouchery/Trigger}
     */
    Trigger,

    /**
     * The User model constructor.
     * @property {module:Vouchery/User}
     */
    User,

    /**
     * The Voucher model constructor.
     * @property {module:Vouchery/Voucher}
     */
    Voucher,

    /**
     * The CampaignsApi service constructor.
     * @property {module:api/CampaignsApi}
     */
    CampaignsApi,

    /**
     * The CategoriesApi service constructor.
     * @property {module:api/CategoriesApi}
     */
    CategoriesApi,

    /**
     * The CustomersApi service constructor.
     * @property {module:api/CustomersApi}
     */
    CustomersApi,

    /**
     * The RedemptionsApi service constructor.
     * @property {module:api/RedemptionsApi}
     */
    RedemptionsApi,

    /**
     * The RewardsApi service constructor.
     * @property {module:api/RewardsApi}
     */
    RewardsApi,

    /**
     * The RulesApi service constructor.
     * @property {module:api/RulesApi}
     */
    RulesApi,

    /**
     * The TriggersApi service constructor.
     * @property {module:api/TriggersApi}
     */
    TriggersApi,

    /**
     * The UsersApi service constructor.
     * @property {module:api/UsersApi}
     */
    UsersApi,

    /**
     * The VouchersApi service constructor.
     * @property {module:api/VouchersApi}
     */
    VouchersApi
};