/**
 * Vouchery API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * Contact: hello@vouchery.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', '../../src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.VoucheryApiReference);
    }
}(this, function(expect, VoucheryApiReference) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new VoucheryApiReference.CustomersApi();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('CustomersApi', function() {
        describe('assignVoucherToCustomer', function() {
            it('should call assignVoucherToCustomer successfully', function(done) {
                //uncomment below and update the code to test assignVoucherToCustomer
                //instance.assignVoucherToCustomer(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('createCustomer', function() {
            it('should call createCustomer successfully', function(done) {
                //uncomment below and update the code to test createCustomer
                //instance.createCustomer(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('deleteCustomer', function() {
            it('should call deleteCustomer successfully', function(done) {
                //uncomment below and update the code to test deleteCustomer
                //instance.deleteCustomer(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('getCustomer', function() {
            it('should call getCustomer successfully', function(done) {
                //uncomment below and update the code to test getCustomer
                //instance.getCustomer(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('getCustomerRedemptions', function() {
            it('should call getCustomerRedemptions successfully', function(done) {
                //uncomment below and update the code to test getCustomerRedemptions
                //instance.getCustomerRedemptions(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('getCustomerVouchers', function() {
            it('should call getCustomerVouchers successfully', function(done) {
                //uncomment below and update the code to test getCustomerVouchers
                //instance.getCustomerVouchers(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('getCustomers', function() {
            it('should call getCustomers successfully', function(done) {
                //uncomment below and update the code to test getCustomers
                //instance.getCustomers(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
    });

}));